#!/usr/bin/env python3
"""Generates GinoHome.xcodeproj/project.pbxproj for the Gino-Home iOS/macOS shell app."""

import os

_counter = [0]
def uid(_=""):
    _counter[0] += 1
    return ("%024X" % _counter[0])

PROJECT          = uid()
MAIN_GROUP       = uid()
PRODUCTS_GROUP   = uid()
TARGET           = uid()
APP_PRODUCT      = uid()

SRC_PHASE        = uid()
RES_PHASE        = uid()
FW_PHASE         = uid()

PROJ_DBG_CFG     = uid()
PROJ_REL_CFG     = uid()
TGT_DBG_CFG      = uid()
TGT_REL_CFG      = uid()
PROJ_CFG_LIST    = uid()
TGT_CFG_LIST     = uid()

GRP_APP          = uid()

SOURCES = [
    (uid(), uid(), "GinoHomeApp.swift",      "GinoHomeApp.swift"),
    (uid(), uid(), "AppConfig.swift",        "AppConfig.swift"),
    (uid(), uid(), "ContentView.swift",      "ContentView.swift"),
    (uid(), uid(), "WebCoordinator.swift",   "WebCoordinator.swift"),
    (uid(), uid(), "WebView.swift",          "WebView.swift"),
]

ASSETS_REF       = uid(); ASSETS_BF        = uid()
INFOPLIST_REF    = uid()
ENTITLEMENTS_REF = uid()

WEBKIT_REF       = uid(); WEBKIT_BF        = uid()

BUNDLE_ID                  = "de.gino-home.app"
PRODUCT_NAME               = "GinoHome"
SWIFT_VERSION              = "5.0"
IPHONEOS_DEPLOYMENT_TARGET = "17.0"
MACCATALYST_DEPLOYMENT     = "17.0"
DEV_TEAM                   = "Z39M824865"


def pbx():
    lines = []
    def w(s=""): lines.append(s)

    w("// !$*UTF8*$!")
    w("{")
    w("\tarchiveVersion = 1;")
    w("\tclasses = {")
    w("\t};")
    w("\tobjectVersion = 56;")
    w("\tobjects = {")
    w()

    w("/* Begin PBXBuildFile section */")
    for (ref, bf, _, name) in SOURCES:
        w(f"\t\t{bf} /* {name} in Sources */ = {{isa = PBXBuildFile; fileRef = {ref} /* {name} */; }};")
    w(f"\t\t{ASSETS_BF} /* Assets.xcassets in Resources */ = {{isa = PBXBuildFile; fileRef = {ASSETS_REF} /* Assets.xcassets */; }};")
    w(f"\t\t{WEBKIT_BF} /* WebKit.framework in Frameworks */ = {{isa = PBXBuildFile; fileRef = {WEBKIT_REF} /* WebKit.framework */; }};")
    w("/* End PBXBuildFile section */")
    w()

    w("/* Begin PBXFileReference section */")
    w(f"\t\t{APP_PRODUCT} /* {PRODUCT_NAME}.app */ = {{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = {PRODUCT_NAME}.app; sourceTree = BUILT_PRODUCTS_DIR; }};")
    for (ref, _, _, name) in SOURCES:
        w(f"\t\t{ref} /* {name} */ = {{isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = {name}; sourceTree = \"<group>\"; }};")
    w(f"\t\t{ASSETS_REF} /* Assets.xcassets */ = {{isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Assets.xcassets; sourceTree = \"<group>\"; }};")
    w(f"\t\t{INFOPLIST_REF} /* Info.plist */ = {{isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = \"<group>\"; }};")
    w(f"\t\t{ENTITLEMENTS_REF} /* GinoHome.entitlements */ = {{isa = PBXFileReference; lastKnownFileType = text.plist.entitlements; path = GinoHome.entitlements; sourceTree = \"<group>\"; }};")
    w(f"\t\t{WEBKIT_REF} /* WebKit.framework */ = {{isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = WebKit.framework; path = System/Library/Frameworks/WebKit.framework; sourceTree = SDKROOT; }};")
    w("/* End PBXFileReference section */")
    w()

    w("/* Begin PBXFrameworksBuildPhase section */")
    w(f"\t\t{FW_PHASE} /* Frameworks */ = {{")
    w(f"\t\t\tisa = PBXFrameworksBuildPhase;")
    w(f"\t\t\tbuildActionMask = 2147483647;")
    w(f"\t\t\tfiles = (")
    w(f"\t\t\t\t{WEBKIT_BF} /* WebKit.framework in Frameworks */,")
    w(f"\t\t\t);")
    w(f"\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    w(f"\t\t}};")
    w("/* End PBXFrameworksBuildPhase section */")
    w()

    w("/* Begin PBXGroup section */")

    w(f"\t\t{MAIN_GROUP} = {{")
    w(f"\t\t\tisa = PBXGroup;")
    w(f"\t\t\tchildren = (")
    w(f"\t\t\t\t{GRP_APP} /* {PRODUCT_NAME} */,")
    w(f"\t\t\t\t{PRODUCTS_GROUP} /* Products */,")
    w(f"\t\t\t);")
    w(f"\t\t\tsourceTree = \"<group>\";")
    w(f"\t\t}};")

    w(f"\t\t{PRODUCTS_GROUP} /* Products */ = {{")
    w(f"\t\t\tisa = PBXGroup;")
    w(f"\t\t\tchildren = (")
    w(f"\t\t\t\t{APP_PRODUCT} /* {PRODUCT_NAME}.app */,")
    w(f"\t\t\t);")
    w(f"\t\t\tname = Products;")
    w(f"\t\t\tsourceTree = \"<group>\";")
    w(f"\t\t}};")

    w(f"\t\t{GRP_APP} /* {PRODUCT_NAME} */ = {{")
    w(f"\t\t\tisa = PBXGroup;")
    w(f"\t\t\tchildren = (")
    for (ref, _, _, name) in SOURCES:
        w(f"\t\t\t\t{ref} /* {name} */,")
    w(f"\t\t\t\t{ASSETS_REF} /* Assets.xcassets */,")
    w(f"\t\t\t\t{INFOPLIST_REF} /* Info.plist */,")
    w(f"\t\t\t\t{ENTITLEMENTS_REF} /* GinoHome.entitlements */,")
    w(f"\t\t\t);")
    w(f"\t\t\tpath = {PRODUCT_NAME};")
    w(f"\t\t\tsourceTree = \"<group>\";")
    w(f"\t\t}};")

    w("/* End PBXGroup section */")
    w()

    w("/* Begin PBXNativeTarget section */")
    w(f"\t\t{TARGET} /* {PRODUCT_NAME} */ = {{")
    w(f"\t\t\tisa = PBXNativeTarget;")
    w(f"\t\t\tbuildConfigurationList = {TGT_CFG_LIST} /* Build configuration list for PBXNativeTarget \"{PRODUCT_NAME}\" */;")
    w(f"\t\t\tbuildPhases = (")
    w(f"\t\t\t\t{SRC_PHASE} /* Sources */,")
    w(f"\t\t\t\t{FW_PHASE} /* Frameworks */,")
    w(f"\t\t\t\t{RES_PHASE} /* Resources */,")
    w(f"\t\t\t);")
    w(f"\t\t\tbuildRules = (")
    w(f"\t\t\t);")
    w(f"\t\t\tdependencies = (")
    w(f"\t\t\t);")
    w(f"\t\t\tname = {PRODUCT_NAME};")
    w(f"\t\t\tproductName = {PRODUCT_NAME};")
    w(f"\t\t\tproductReference = {APP_PRODUCT} /* {PRODUCT_NAME}.app */;")
    w(f"\t\t\tproductType = \"com.apple.product-type.application\";")
    w(f"\t\t}};")
    w("/* End PBXNativeTarget section */")
    w()

    w("/* Begin PBXProject section */")
    w(f"\t\t{PROJECT} /* Project object */ = {{")
    w(f"\t\t\tisa = PBXProject;")
    w(f"\t\t\tattributes = {{")
    w(f"\t\t\t\tBuildIndependentTargetsInParallel = 1;")
    w(f"\t\t\t\tLastSwiftUpdateCheck = 1500;")
    w(f"\t\t\t\tLastUpgradeCheck = 1500;")
    w(f"\t\t\t\tTargetAttributes = {{")
    w(f"\t\t\t\t\t{TARGET} = {{")
    w(f"\t\t\t\t\t\tCreatedOnToolsVersion = 15.0;")
    w(f"\t\t\t\t\t}};")
    w(f"\t\t\t\t}};")
    w(f"\t\t\t}};")
    w(f"\t\t\tbuildConfigurationList = {PROJ_CFG_LIST} /* Build configuration list for PBXProject \"{PRODUCT_NAME}\" */;")
    w(f"\t\t\tcompatibilityVersion = \"Xcode 14.0\";")
    w(f"\t\t\tdevelopmentRegion = de;")
    w(f"\t\t\thasScannedForEncodings = 0;")
    w(f"\t\t\tknownRegions = (")
    w(f"\t\t\t\tde,")
    w(f"\t\t\t\tBase,")
    w(f"\t\t\t);")
    w(f"\t\t\tmainGroup = {MAIN_GROUP};")
    w(f"\t\t\tproductRefGroup = {PRODUCTS_GROUP} /* Products */;")
    w(f"\t\t\tprojectDirPath = \"\";")
    w(f"\t\t\tprojectRoot = \"\";")
    w(f"\t\t\ttargets = (")
    w(f"\t\t\t\t{TARGET} /* {PRODUCT_NAME} */,")
    w(f"\t\t\t);")
    w(f"\t\t}};")
    w("/* End PBXProject section */")
    w()

    w("/* Begin PBXResourcesBuildPhase section */")
    w(f"\t\t{RES_PHASE} /* Resources */ = {{")
    w(f"\t\t\tisa = PBXResourcesBuildPhase;")
    w(f"\t\t\tbuildActionMask = 2147483647;")
    w(f"\t\t\tfiles = (")
    w(f"\t\t\t\t{ASSETS_BF} /* Assets.xcassets in Resources */,")
    w(f"\t\t\t);")
    w(f"\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    w(f"\t\t}};")
    w("/* End PBXResourcesBuildPhase section */")
    w()

    w("/* Begin PBXSourcesBuildPhase section */")
    w(f"\t\t{SRC_PHASE} /* Sources */ = {{")
    w(f"\t\t\tisa = PBXSourcesBuildPhase;")
    w(f"\t\t\tbuildActionMask = 2147483647;")
    w(f"\t\t\tfiles = (")
    for (_, bf, _, name) in SOURCES:
        w(f"\t\t\t\t{bf} /* {name} in Sources */,")
    w(f"\t\t\t);")
    w(f"\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    w(f"\t\t}};")
    w("/* End PBXSourcesBuildPhase section */")
    w()

    w("/* Begin XCBuildConfiguration section */")

    w(f"\t\t{PROJ_DBG_CFG} /* Debug */ = {{")
    w(f"\t\t\tisa = XCBuildConfiguration;")
    w(f"\t\t\tbuildSettings = {{")
    w(f"\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;")
    w(f"\t\t\t\tCLANG_ANALYZER_NONNULL = YES;")
    w(f"\t\t\t\tCLANG_CXX_LANGUAGE_STANDARD = \"gnu++20\";")
    w(f"\t\t\t\tCOPY_PHASE_STRIP = NO;")
    w(f"\t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;")
    w(f"\t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;")
    w(f"\t\t\t\tENABLE_TESTABILITY = YES;")
    w(f"\t\t\t\tGCC_C_LANGUAGE_STANDARD = gnu17;")
    w(f"\t\t\t\tGCC_DYNAMIC_NO_PIC = NO;")
    w(f"\t\t\t\tGCC_OPTIMIZATION_LEVEL = 0;")
    w(f"\t\t\t\tGCC_PREPROCESSOR_DEFINITIONS = (\"DEBUG=1\", \"$(inherited)\");")
    w(f"\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = {IPHONEOS_DEPLOYMENT_TARGET};")
    w(f"\t\t\t\tMTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;")
    w(f"\t\t\t\tMTL_FAST_MATH = YES;")
    w(f"\t\t\t\tONLY_ACTIVE_ARCH = YES;")
    w(f"\t\t\t\tSDKROOT = iphoneos;")
    w(f"\t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;")
    w(f"\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-Onone\";")
    w(f"\t\t\t}};")
    w(f"\t\t\tname = Debug;")
    w(f"\t\t}};")

    w(f"\t\t{PROJ_REL_CFG} /* Release */ = {{")
    w(f"\t\t\tisa = XCBuildConfiguration;")
    w(f"\t\t\tbuildSettings = {{")
    w(f"\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;")
    w(f"\t\t\t\tCLANG_ANALYZER_NONNULL = YES;")
    w(f"\t\t\t\tCLANG_CXX_LANGUAGE_STANDARD = \"gnu++20\";")
    w(f"\t\t\t\tCOPY_PHASE_STRIP = NO;")
    w(f"\t\t\t\tDEBUG_INFORMATION_FORMAT = \"dwarf-with-dsym\";")
    w(f"\t\t\t\tENABLE_NS_ASSERTIONS = NO;")
    w(f"\t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;")
    w(f"\t\t\t\tGCC_C_LANGUAGE_STANDARD = gnu17;")
    w(f"\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = {IPHONEOS_DEPLOYMENT_TARGET};")
    w(f"\t\t\t\tMTL_ENABLE_DEBUG_INFO = NO;")
    w(f"\t\t\t\tMTL_FAST_MATH = YES;")
    w(f"\t\t\t\tSDKROOT = iphoneos;")
    w(f"\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;")
    w(f"\t\t\t\tVALIDATE_PRODUCT = YES;")
    w(f"\t\t\t}};")
    w(f"\t\t\tname = Release;")
    w(f"\t\t}};")

    def target_config(cid, name, is_debug):
        w(f"\t\t{cid} /* {name} */ = {{")
        w(f"\t\t\tisa = XCBuildConfiguration;")
        w(f"\t\t\tbuildSettings = {{")
        w(f"\t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;")
        w(f"\t\t\t\tASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;")
        w(f"\t\t\t\tCODE_SIGN_ENTITLEMENTS = {PRODUCT_NAME}/{PRODUCT_NAME}.entitlements;")
        w(f"\t\t\t\tCODE_SIGN_STYLE = Automatic;")
        w(f"\t\t\t\tDEVELOPMENT_TEAM = {DEV_TEAM};")
        w(f"\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
        w(f"\t\t\t\tGENERATE_INFOPLIST_FILE = NO;")
        w(f"\t\t\t\tINFOPLIST_FILE = {PRODUCT_NAME}/Info.plist;")
        w(f"\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = {IPHONEOS_DEPLOYMENT_TARGET};")
        w(f"\t\t\t\tMARKETING_VERSION = 1.0;")
        w(f"\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = \"{BUNDLE_ID}\";")
        w(f"\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
        w(f"\t\t\t\tSDKROOT = iphoneos;")
        w(f"\t\t\t\tSUPPORTS_MACCATALYST = YES;")
        w(f"\t\t\t\tSUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD = NO;")
        w(f"\t\t\t\tSUPPORTED_PLATFORMS = \"iphoneos iphonesimulator macosx\";")
        w(f"\t\t\t\tDERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER = NO;")
        w(f"\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = {IPHONEOS_DEPLOYMENT_TARGET};")
        w(f"\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 14.0;")
        w(f"\t\t\t\tSWIFT_VERSION = {SWIFT_VERSION};")
        w(f"\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";")
        w(f"\t\t\t\tINFOPLIST_KEY_CFBundleDisplayName = \"Gino-Home\";")
        if not is_debug:
            w(f"\t\t\t\tVALIDATE_PRODUCT = YES;")
        w(f"\t\t\t}};")
        w(f"\t\t\tname = {name};")
        w(f"\t\t}};")

    target_config(TGT_DBG_CFG, "Debug", True)
    target_config(TGT_REL_CFG, "Release", False)
    w("/* End XCBuildConfiguration section */")
    w()

    w("/* Begin XCConfigurationList section */")
    w(f"\t\t{PROJ_CFG_LIST} /* Build configuration list for PBXProject \"{PRODUCT_NAME}\" */ = {{")
    w(f"\t\t\tisa = XCConfigurationList;")
    w(f"\t\t\tbuildConfigurations = (")
    w(f"\t\t\t\t{PROJ_DBG_CFG} /* Debug */,")
    w(f"\t\t\t\t{PROJ_REL_CFG} /* Release */,")
    w(f"\t\t\t);")
    w(f"\t\t\tdefaultConfigurationIsVisible = 0;")
    w(f"\t\t\tdefaultConfigurationName = Release;")
    w(f"\t\t}};")
    w(f"\t\t{TGT_CFG_LIST} /* Build configuration list for PBXNativeTarget \"{PRODUCT_NAME}\" */ = {{")
    w(f"\t\t\tisa = XCConfigurationList;")
    w(f"\t\t\tbuildConfigurations = (")
    w(f"\t\t\t\t{TGT_DBG_CFG} /* Debug */,")
    w(f"\t\t\t\t{TGT_REL_CFG} /* Release */,")
    w(f"\t\t\t);")
    w(f"\t\t\tdefaultConfigurationIsVisible = 0;")
    w(f"\t\t\tdefaultConfigurationName = Release;")
    w(f"\t\t}};")
    w("/* End XCConfigurationList section */")
    w()

    w("\t};")
    w(f"\trootObject = {PROJECT} /* Project object */;")
    w("}")

    return "\n".join(lines)


if __name__ == "__main__":
    base = os.path.dirname(os.path.abspath(__file__))
    proj_dir = os.path.join(base, "GinoHome.xcodeproj")
    os.makedirs(proj_dir, exist_ok=True)
    out = os.path.join(proj_dir, "project.pbxproj")
    with open(out, "w") as f:
        f.write(pbx())
    print(f"Generated: {out}")
